### PR TITLE
deps: upgrade pretty_assertions and itertools

### PR DESCRIPTION
**Pull request by secretfader**
This PR updates itertools and pretty_assertions to the latest versions. Tests passed locally (on Fedora Linux 29) but if there's anything I need to check for other platforms, let me know.

### CODE REVIEW

**Comment by secretfader** [comment]
Looking at CI, it appears the failures are because some dependencies require a newer version of Rust. I upgraded Travis `rustc`, and will update the `README` too if CI passes.

**Comment by DarkEld3r** [comment]
Many thanks for the pull requests! Lately I have abandoned this project a little bit. I have migrated it to the 2018 edition: https://github.com/DarkEld3r/os_info/pull/96
I'm going to merge your pull request right after merging migration.

**Comment by secretfader** [comment]
I'm glad to help however I can. Should I rebase this PR?

**Comment by DarkEld3r** [comment]
@secretfader That would be great, thanks.

**Comment by DarkEld3r** [comment]
@secretfader Thanks.

It isn't related to your pull request, but could you please fix the Appveyor build? I suppose this will do the trick:
```diff
--- a/src/windows/mod.rs
+++ b/src/windows/mod.rs
@@ -14,7 +14,7 @@ pub fn current_platform() -> Info {
 #[cfg(test)]
 mod tests {
     use super::*;
-    use Type;
+    use crate::Type;
 
     #[test]
     fn os_type() {
```

**Comment by secretfader** [comment]
@DarkEld3r I saw that one slip in, I assume when I re-based against the 2018 update. I updated the import syntax, it should pass CI now.

**Comment by DarkEld3r** [comment]
@secretfader Thanks. I suppose you would like to see a new version published with these updates?

**Comment by secretfader** [comment]
@DarkEld3r Indeed, it would be nice to clean up warnings on compile. Thank you handling the PRs so quickly.

**Comment by DarkEld3r** [comment]
@secretfader The `1.1.1` version is available on crates.io. :tada:

**Pull request merged**
