### PR TITLE
updated macos::current_platform to process the product version correctly

### PR DESCRIPTION
**Pull request by DannyPeck**

### CODE REVIEW

**Comment by DarkEld3r** [comment]
Thank you for the pull request. Could you please fix [formatting](https://travis-ci.org/DarkEld3r/os_info/jobs/328957715)?

**Comment by DannyPeck** [comment]
No problem!  Sure, although I am not really sure what the problem is... I looked at the Travis CI output and couldn't ascertain the formatting issue.  If you let me know what the issue is I will gladly fix it :).

**Comment by DarkEld3r** [comment]
It is a bit controversial, but I'm using `rust-fmt 0.9.0` in Travis. As you can see in the [build output](https://travis-ci.org/DarkEld3r/os_info/jobs/328957715) (725 line), the following patch should be applied to make the build successful:
```rust
Diff in /home/travis/build/DarkEld3r/os_info/src/macos/mod.rs at line 10:
 ⏎
 pub fn current_platform() -> Info {⏎
     let version = match retrieve().map(|x| x.product_version) {⏎
-        Some(version) => match version {⏎
-            Some(v) => Version::custom(v, None),⏎
-            None => Version::unknown(),⏎
-        },⏎
+        Some(version) => {⏎
+            match version {⏎
+                Some(v) => Version::custom(v, None),⏎
+                None => Version::unknown(),⏎
+            }⏎
+        }⏎
         None => Version::unknown(),⏎
     };⏎
 ⏎
```

**Comment by DannyPeck** [comment]
Thanks! I updated the format to include the braces.  It appears that travis-ci could not complete for some reason, you could try rerunning the check.  I also noticed that it took travis-ci a very long time to complete, thought it was worth mentioning.

**Comment by DarkEld3r** [comment]
Thank you for the update. I'm going to merge it and release a new version as soon as possible, sorry for the delay.

There are some problems with the build for sure: I'm going to try to fix them. :sweat_smile:

**Comment by DannyPeck** [comment]
No worries, thanks!  And thank you for being an active maintainer haha 😅.

**Pull request merged**
